// Generated by jextract

package com.github.doblon8.jzbar.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct video_control_menu_s {
 *     char *name;
 *     int64_t value;
 * } video_control_menu_t
 * }
 */
public class video_control_menu_t extends video_control_menu_s {

    video_control_menu_t() {
        // Should not be called directly
    }
}

