// Generated by jextract

package com.github.doblon8.jzbar.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct video_controls_s {
 *     char *name;
 *     char *group;
 *     video_control_type_t type;
 *     int64_t min;
 *     int64_t max;
 *     int64_t def;
 *     uint64_t step;
 *     unsigned int menu_size;
 *     video_control_menu_t *menu;
 *     void *next;
 * } video_controls_t
 * }
 */
public class video_controls_t extends video_controls_s {

    video_controls_t() {
        // Should not be called directly
    }
}

