// Generated by jextract

package io.github.doblon8.jzbar.bindings;

/**
 * {@snippet lang=c :
 * typedef struct video_control_menu_s {
 *     char *name;
 *     int64_t value;
 * } video_control_menu_t
 * }
 */
public class video_control_menu_t extends video_control_menu_s {

    video_control_menu_t() {
        // Should not be called directly
    }
}

